server:
  port: 8080
logging:
  level:
    uniresolver.driver.did.icon: debug
app:
  debug: false
  networks:
    -
      nodeUrl: https://ctz.solidwallet.io/api/v3
      didScore: cx694e8c9f1a05c8c3719f30d46b97697960e4289e
      networkId: 1
    -
      nodeUrl: https://sejong.net.solidwallet.io/api/v3
      didScore: cxc7c8b0bb85eca64aecc8cc38628c4bc3c449f1fd
      networkId: 83
    -
      nodeUrl: ${uniresolver_driver_did_icon_node_url}
      didScore: ${uniresolver_driver_did_icon_score_addr}
      networkId: ${uniresolver_driver_did_icon_network_id}
